name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: install FE dependencies
        run: yarn
        working-directory: ./Meilensteine/Meilenstein_04/frontend
      - name: run FE tests & linter
        run: yarn sonar || echo Done
        working-directory: ./Meilensteine/Meilenstein_04/frontend
      - name: patch ESLint result
        run:  sed -i 's+/home/runner/work/Softwarepraktikum/Softwarepraktikum+/github/workspace+g' eslint.json
        working-directory: ./Meilensteine/Meilenstein_04/frontend/coverage

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt
        working-directory: ./Meilensteine/Meilenstein_04/

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml
        working-directory: ./Meilensteine/Meilenstein_04/
      - name: patch PyTest result
        run:  sed -i 's+/home/runner/work/Softwarepraktikum/Softwarepraktikum+/github/workspace+g' coverage.xml
        working-directory: ./Meilensteine/Meilenstein_04/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
