name: puml-to-img
on:
  push:
    paths: ['**.puml']
jobs:

  puml-to-svg:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#')"
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.schmidti2002 }}
          fetch-depth: 0

      # signed commits
      - name: import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.schmidti2002_GPG_PRIVATE }}
          passphrase: ${{ secrets.schmidti2002_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: convert files
        uses: grassedge/generate-plantuml-action@master
        with:
          message: '[chore] rendered SVGs'
        env:
          GITHUB_TOKEN: ${{ secrets.schmidti2002 }}

  puml-to-png:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#')"
    needs: puml-to-svg
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.schmidti2002 }}
          fetch-depth: 0


      - name: install plantuml
        run: |
          sudo apt install graphviz
          sudo apt install nodejs
          npm install -g node-plantuml

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5

      - name: convert files
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            if [[ $changed_file == **.puml ]]
            then
              puml generate $changed_file -o ${changed_file//.puml/.png}
            fi
          done

      - run: git pull

      # signed commits
      - name: import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.schmidti2002_GPG_PRIVATE }}
          passphrase: ${{ secrets.schmidti2002_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      # commit changed pom file
      - name: auto commit
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '**.png'
          commit_message: '[chore] rendered PNGs'
          commit_user_name: 'schmidti2002'
          commit_user_email: 'florian-hartha@web.de'
